pipeline {
    agent any

    
    stages {
        // stage('Checkout') {
        //     steps {
        //         // Pull code from your SCM (e.g., GitHub)
        //         checkout scm
        //     }
        // }

        stage('Build Maven Project') {
            steps {
                dir('my-app') {
                    // Build the Maven project
                sh "mvn clean install"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir ('my-app') {
                    // Build the Docker image
                    sh """
                       docker build -t my-custom-app:2.0 .
                    """
                }
            
            }
        }
         stage('Run Docker Image') {
            steps {
                dir ('my-app') {
                    // Run the Docker image
                    sh """
                       docker run -p 8090:8080 my-custom-app:2.0 .
                    """
                }
            
            }
        }
}
